apiVersion: v1
kind: PersistentVolume
metadata:
  name: tezos-node
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/tezos/node"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tezos-client
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/tezos/client"
