apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: node
  namespace: tezos
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: node
  ports:
  - name: p2p
    port: 9732
  - name: rpc
    port: 8732
