apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
  namespace: tezos
  labels:
    app: node
spec:
  serviceName: node
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-node
        image: registry.local/tezos-node-init:dev
        volumeMounts:
        - name: data
          mountPath: /home/tezos/.tezos-node
        - name: snapshot
          mountPath: /home/tezos/.tezos-snapshots
      containers:
      - name: node
        image: registry.local/tezos-node:v8.0
        ports:
        - containerPort: 9732
          name: p2p
        - containerPort: 8732
          name: rpc
        volumeMounts:
        - name: data
          mountPath: /home/tezos/.tezos-node
        resources:
          requests:
            cpu: 1000m
            memory: 6Gi
          limits:
            cpu: 1000m
            memory: 6Gi
        startupProbe:
          httpGet:
            path: /chains/main/blocks/head/header
            port: 8732
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /chains/main/blocks/head/header
            port: 8732
          periodSeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/nodecheck
          periodSeconds: 65
          timeoutSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local
      resources:
        requests:
          storage: 100Gi
  - metadata:
      name: snapshot
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local
      resources:
        requests:
          storage: 10Gi
